# Generated by Django 5.2.2 on 2025-06-20 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_task_options_remove_task_completed_task_status_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Todo',
        ),
    ]
